### ISSUE TITLE
Error on version bump: Resource not accessible by integration

### ISSUE THREAD

**Issue by maxhollmann** [jefflinse/pr-semver-bump#42]
I'm getting the error `unexpected error: Resource not accessible by integration`  when running the version bump [here](https://github.com/maxhollmann/github-workflow-tests/actions/runs/4812439092/jobs/8567686804).

Here's the [definition](https://github.com/maxhollmann/github-workflow-tests/blob/master/.github/workflows/release.yml) for the failing workflow.

**Comment by ImDevinC** [comment]
I am getting this same issue, although I'm using a shared workflow. I've outlined the shared workflow as well as how I'm calling it, and the subsequent logs. Note that calling the validate action from a shared workflow does show proper version detection, and it looks to be failing only when trying to actually create the tag.

<details>
<summary>Shared workflow</summary>

```yaml
name: Bump SemVer Tags

on:
  workflow_call:
    inputs:
      include-v-prefix:
        description: "Include V prefix on published version"
        default: true
        required: false
        type: boolean

jobs:
  bump-tag-version:
    name: Bump and tag version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate PR metadata
        uses: jefflinse/pr-semver-bump@v1.6.0
        id: bump
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          minor-label: minor
          major-label: major
          patch-label: patch
          with-v: ${{ inputs.include-v-prefix }}
```

</details>

<details>
<summary>Calling Workflow</summary>

```yaml
name: Bump SemVer Tags

on:
  push:
    branches:
      - main

jobs:
  bump-semver:
    uses: imdevinc/imdevinc/.github/workflows/shared-bump-semver-tags.yaml@v1
    secrets: inherit
```

</details>

<details>
<summary>Logs</summary>

```
Run jefflinse/pr-semver-bump@v1.6.0
  with:
    mode: bump
    repo-token: ***
    minor-label: minor
    major-label: major
    patch-label: patch
    with-v: true
    require-release-notes: false
    base-branch: false
Processing version bump for PR request #[2](https://github.com/ImDevinC/go-links/actions/runs/7687696738/job/20948027591#step:3:2)
HttpError: Resource not accessible by integration
    at /home/runner/work/_actions/jefflinse/pr-semver-bump/v1.6.0/webpack:/pr-semver-bump/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (node:internal/process/task_queues:96:[5](https://github.com/ImDevinC/go-links/actions/runs/7687696738/job/20948027591#step:3:5))
    at createRelease (/home/runner/work/_actions/jefflinse/pr-semver-bump/v1.[6](https://github.com/ImDevinC/go-links/actions/runs/7687696738/job/20948027591#step:3:6).0/webpack:/pr-semver-bump/version.js:51:1)
    at bumpAndTagNewVersion (/home/runner/work/_actions/jefflinse/pr-semver-bump/v1.6.0/webpack:/pr-semver-bump/index.js:[9](https://github.com/ImDevinC/go-links/actions/runs/7687696738/job/20948027591#step:3:9)0:1)
    at run (/home/runner/work/_actions/jefflinse/pr-semver-bump/v1.6.0/webpack:/pr-semver-bump/index.js:[10](https://github.com/ImDevinC/go-links/actions/runs/7687696738/job/20948027591#step:3:10)6:1)
Error: unexpected error: Resource not accessible by integration
```

</details>

**Comment by ImDevinC** [comment]
This was my fault, I was missing the following permissions (which are documented:

```yaml
permissions:
  contents: write
  issues: read
  pull-requests: read
```
