### ISSUE TITLE
Reference Update Failed on bump

### ISSUE THREAD

**Issue by jaredbarranco** [jefflinse/pr-semver-bump#45]
See below screenshot:
![image](https://github.com/jefflinse/pr-semver-bump/assets/51723690/b2587eeb-53c7-4048-83cf-6ba2aa8b3a1a)

Below is the workflow file that triggers the error:

```
name: AutoTag SemVer Git Tag
on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      continue-on-error:
        type: boolean
        required: false
        default: false

jobs:
  bump-tag-version:
    name: Bump and Tag Version
    runs-on: ubuntu-latest
    continue-on-error: ${{inputs.continue-on-error}}
    permissions:
      contents: write
      issues: read
      pull-requests: read
    steps:
      - uses: jefflinse/pr-semver-bump@v1
        name: Bump and Tag Version
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          require-release-notes: false
          with-v: true
          base-branch: true
          
      - name: Warn on Failure
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            core.warning(`Semantic Version Pip Failed! Check your PR Labels!`);
```

The explicit permissions are being granted by the calling workflow.

Happy to provide additional information as requested.
