### ISSUE TITLE
noop-labels not working

### ISSUE THREAD

**Issue by dza89** [jefflinse/pr-semver-bump#49]
Noob labels don't seem to work, config:

```yaml
            - uses: jefflinse/pr-semver-bump@v1.6.0
              name: labels
              with:
                  mode: validate
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  major-label: major
                  minor-label: minor
                  noop-labels:
                    - documentation change
                  patch-label: patch

```

Results in a:
`
The workflow is not valid. .github/workflows/pull_request.yaml (Line: 110, Col: 21): A sequence was not expected
`

When I remove noop-labels it works fine. 
The default in action.yaml is also an empty string, so something is up.

**Comment by jefflinse** [comment]
@dza89 When you said it works as a string, do you mean that it works (and only works) when quoting the value? E.g.

```yaml
noop-labels:
  - "documentation change"
```

**Comment by dza89** [comment]
No, it works only as

noop-labels: "documentation change"

**Comment by AbstractVersion** [comment]
> No, it works only as
> 
> noop-labels: "documentation change"

is it comma seperated eg. `"documentation change, another label, etc"` ?

**Comment by rtizzy** [comment]
@jefflinse 

I can confirm the syntax is correct when passed in as a string as dza89 mentions. 

Unfortunately the "no-op" still does not work. 

As an example:

```
jobs:
  check-pr:
    name: Validate Release Label and Notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jefflinse/pr-semver-bump@v1.6.0
        name: Validate Pull Request Metadata
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major
          minor-label: minor
          patch-label: patch
          # NOTE: Fix this when it's handled upstream
          noop-labels: nobump
```

Adding the nobump label to the PR still results in the following error

```
  with:
    mode: validate
    repo-token: ***
    major-label: major
    minor-label: minor
    patch-label: patch
    require-release-notes: false
    with-v: false
    base-branch: false
Error: PR validation failed: no release label specified on PR
```

**Comment by rtizzy** [comment]
For some additional context, this still does not work but it will at least be fed into the `with`

```
jobs:
  check-pr:
    name: Validate Release Label and Notes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jefflinse/pr-semver-bump@v1.6.0
        name: Validate Pull Request Metadata
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: major
          minor-label: minor
          patch-label: patch
          # NOTE: Fix this when it's handled upstream
          noop-labels: 
            nobump
            testing
```

```
Run jefflinse/pr-semver-bump@v1.6.0
  with:
    mode: validate
    repo-token: ***
    major-label: major
    minor-label: minor
    patch-label: patch
    noop-labels: nobump testing
    require-release-notes: false
    with-v: false
    base-branch: false
```
